global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'books_app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          # IP in MacOS:
          # ifconfig | grep "inet " | grep -v 127.0.0.1
          - '192.168.1.20:8080'
